name: mpich
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout vol-daos
      uses: actions/checkout@v3
    - name: Checkout DAOS
      uses: actions/checkout@v3
      with:
        repository: daos-stack/daos
        submodules: recursive
        path: daos
    - name: Checkout HDF5
      uses: actions/checkout@v3
      with:
        repository: HDFGroup/hdf5
        path: hdf5
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -q -y \
          autoconf \
          build-essential \
          clang \
          clang-format \
          cmake \
          curl \
          dpdk \
          fuse3 \
          git \
          golang-go \
          kmod \
          libaio-dev \
          libboost-dev \
          libcmocka-dev \
          libcunit1-dev \
          libfuse3-dev \
          libhwloc-dev \
          libibverbs-dev \
          libipmctl-dev \
          libjson-c-dev \
          liblz4-dev \
          libnuma-dev \
          libmd-dev \
          libmpich-dev \
          libprotobuf-c-dev \
          librdmacm-dev \
          libssl-dev \
          libtool-bin \
          libunwind-dev \
          libyaml-dev \
          locales \
          maven \
          mpich \
          numactl \
          openjdk-8-jdk \
          patchelf \
          pciutils \
          pkg-config \
          python3-dev \
          python3-venv \
          scons \
          uuid-dev \
          valgrind \
          yasm
    - name: Install DAOS
      run: |
        cd daos
        sudo pip install -r requirements.txt
        sudo scons --build-deps=yes PREFIX=/usr/local install
        cd ..
    - name: Install HDF5
      run: |
        cmake --version
        mkdir hdf5/build
        cd hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_THREADSAFE:BOOL=ON -DALLOW_UNSUPPORTED:BOOL=ON -DHDF5_ENABLE_MAP_API=ON ..
        sudo make -j install
        cd ..
        git rev-parse HEAD > git.txt
    - name: Install vol-daos
      env:
        CXX: mpic++
        CC: mpicc
        HDF5_PLUGIN_PATH: /usr/local/lib
        HDF5_VOL_CONNECTOR: daos
        LD_LIBRARY_PATH: /usr/local/lib:$LD_LIBRARY_PATH
      run: |
        set
        /usr/bin/mpiexec --version
        mkdir build
        cd build
        cmake .. -DHDF5_DIR=/usr/local -DBUILD_TESTING=ON 
        sudo make -j install
        ls /usr/local/lib
        sudo ctest --output-on-failure
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: git.txt
        path: ${{ runner.workspace }}/vol-daos/hdf5/git.txt
