name: sunspot cron

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '25 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout vol-daos
      uses: actions/checkout@v3    
    - name: cURL request
      run: curl -s -o out.json 'https://mercury-cdash.hdfgroup.org/api/v1/index.php?project=HDF5_VOL_DAOS'
    - id: date
      run: echo "##[set-output name=data;]$(python ./bin/cdash.py)"
    - name: Time badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: sunspot
        LABEL: 'Sunspot Test Failures'
        STATUS: ${{ steps.date.outputs.data }}
        COLOR: 00EEFF
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY: hyoklee/vol-daos
        ACTOR: hyoklee
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: out.json
        path: ${{ runner.workspace }}/out.json
      
        